// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for continent documents */
interface ContinentDocumentData {
    /**
     * Title field in *continent*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Summary field in *continent*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.summary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    summary: prismicT.KeyTextField;
    /**
     * Description field in *continent*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Slider Image field in *continent*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.slider_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slider_image: prismicT.ImageField<never>;
    /**
     * Banner Image field in *continent*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.banner_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    banner_image: prismicT.ImageField<never>;
    /**
     * Countries field in *continent*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.countries
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    countries: prismicT.NumberField;
    /**
     * Languages field in *continent*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.languages
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    languages: prismicT.NumberField;
    /**
     * Cities field in *continent*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    cities: prismicT.NumberField;
    /**
     * Cities List field in *continent*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities_list
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cities_list: prismicT.KeyTextField;
    /**
     * Cities100 field in *continent*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities100[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    cities100: prismicT.GroupField<Simplify<ContinentDocumentDataCities100Item>>;
}
/**
 * Item in continent → Cities100
 *
 */
export interface ContinentDocumentDataCities100Item {
    /**
     * Thumbnail field in *continent → Cities100*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities100[].thumbnail
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * Flag field in *continent → Cities100*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities100[].flag
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    flag: prismicT.ImageField<never>;
    /**
     * City field in *continent → Cities100*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities100[].city
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    city: prismicT.KeyTextField;
    /**
     * Country field in *continent → Cities100*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.cities100[].country
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    country: prismicT.KeyTextField;
}
/**
 * continent document from Prismic
 *
 * - **API ID**: `continent`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContinentDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ContinentDocumentData>, "continent", Lang>;
export type AllDocumentTypes = ContinentDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ContinentDocumentData, ContinentDocumentDataCities100Item, ContinentDocument, AllDocumentTypes };
    }
}
